import = [
    "~/.config/alacritty/themes/rose-pine.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraMono Nerd Font Mono", style = "Regular" }
bold = { family = "FiraMono Nerd Font Mono", style = "Bold" }
offset = { x = 0, y = 1 }
size = 14
