#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    dirs=$(find ~/work ~/personal ~/second-brain -mindepth 1 -maxdepth 1 -type d; echo "$HOME/.dotfiles" ; echo "$HOME/second-brain")
    selected=$(echo -n "$dirs" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

echo "starting"

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    echo "starting tmux"
    echo "tmux new-session -s $selected_name -c $selected"
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    echo "creating session"
    echo "tmux new-session -ds $selected_name -c $selected"
    tmux new-session -ds $selected_name -c $selected
fi

echo "tmux switch-client -t $selected_name"
tmux switch-client -t $selected_name
